/*
  Warnings:

  - The values [roads,streetlights,waste,water,parks,other,ADVERTISEMENT,ARCHITECTURE_DEPARTMENT,ASSESSMENT_AND_COLLECTION_DEPARTMENT,AYUSH_DEPARTMENT,BUILDING_DEPARTMENT,CENTRAL_ESTABLISHMENT,COMMITTEE_AND_CORPORATION,COMMUNITY_SERVICES,DIRECTORATE_OF_INQUIRY,DIRECTORATE_OF_PRESS_AND_INFORMATION,ENVIRONMENTAL_MANAGEMENT,EDUCATION,ELECTION_DEPARTMENT,ENGINEERING_DEPARTMENT,ELECTRICAL_AND_MECHANICAL_DEPARTMENT,FACTORY_LICENSE,FINANCE_DEPARTMENT,HACKNEY_CARRIAGE,HORTICULTURE_DEPARTMENT,HOSPITAL_ADMINISTRATION,INFORMATION_TECHNOLOGY,LABOUR_WELFARE_DEPARTMENT,LAND_AND_ESTATE,LANGUAGE_DEPARTMENT,LAW_DEPARTMENT,LICENSING_DEPARTMENT,MUNICIPAL_SECRETARY_OFFICE,ORGANIZATION_AND_METHOD_DEPARTMENT,PUBLIC_HEALTH_DEPARTMENT,REMUNERATIVE_PROJECT_CELL,STATUTORY_AUDIT_DEPARTMENT,TOWN_PLANNING,TOLL_TAX,VETERINARY,VIGILANCE] on the enum `Category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."Category_new" AS ENUM ('ANIMAL_HUSBANDRY', 'ELECTRICITY_AND_POWER_SUPPLY', 'GARBAGE_AND_USANITARY_PRACTICES', 'PARKS_AND_RECREATION', 'POLLUTION', 'PUBLIC_TOILETS', 'PUBLIC_TRANSPORT', 'ROADS_AND_FOOTPATHS', 'SEWERAGE_SYSTEMS', 'STREET_LIGHTING', 'TRAFFIC_AND_ROAD_SAFETY', 'TREES_AND_SAPLINGS', 'WATER_SUPPLY_AND_SERVICES');
ALTER TABLE "public"."Complaint" ALTER COLUMN "category" TYPE "public"."Category_new" USING ("category"::text::"public"."Category_new");
ALTER TYPE "public"."Category" RENAME TO "Category_old";
ALTER TYPE "public"."Category_new" RENAME TO "Category";
DROP TYPE "public"."Category_old";
COMMIT;
